accounts/urls.py
from django.urls import path

from . import views


app_name = 'accounts'
urlpatterns = [
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.LoginView.as_view(), name='login'),
    path('logout/', views.logout, name='logout'),
]

articles/urls.py
from django.urls import path

from . import views


app_name = 'articles'
urlpatterns = [
    path('', views.index, name='index'),
    path('articles/', views.ArticleListView.as_view(), name='articles'),
    path('articles/add/', views.ArticleCreateView.as_view(), name='article_add'),
    path('articles/<int:pk>/', views.ArticleView.as_view(), name='article_detail'),
    path('publications/', views.PublicationListView.as_view(), name='publications'),
    path('favorites/', views.UserFavoriteArticleListView.as_view(), name='favorites'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User


class Article(models.Model):

    title = models.CharField(max_length=64)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    created = models.DateField(auto_now_add=True)
    synopsis = models.CharField(max_length=312)
    content = models.TextField()

    def __str__(self):
        return self.title


class UserFavoriteArticle(models.Model):

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='favorite')

    class Meta:
        unique_together = ('user', 'article')

    def __str__(self):
        return self.article.title

articles/forms.py
from django.forms import ModelForm

from .models import UserFavoriteArticle


class UserFavoriteArticleForm(ModelForm):

    class Meta:
        model = UserFavoriteArticle
        fields = []

accounts/views.py
from django.contrib import auth
from django.urls import reverse
from django.shortcuts import redirect
from django.views.generic.edit import CreateView
from django.contrib.auth.forms import UserCreationForm


class SignupView(CreateView):

    form_class = UserCreationForm
    template_name = 'accounts/signup.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('articles:index')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('articles:index')


class LoginView(auth.views.LoginView):

    template_name = 'accounts/login.html'

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('articles:index')
        return super().dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse('articles:index')


def logout(request):
    auth.logout(request)
    return redirect('articles:index')

articles/views.py
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import CreateView, FormView
from django.views.generic.detail import DetailView, SingleObjectMixin
from django.views import View
from django.shortcuts import redirect
from django.urls import reverse

from .models import Article, UserFavoriteArticle
from .forms import UserFavoriteArticleForm


def index(request):
    return redirect('articles:articles')


class ArticleListView(ListView):

    model = Article
    context_object_name = 'articles'
    queryset = Article.objects.order_by('created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['headlines'] = (
            'Title', 'Synopsis', 'Author',
            'Created', 'When', '')
        return context


class ArticleDetailView(DetailView):

    model = Article

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = UserFavoriteArticleForm
        return context


class UserFavoriteArticleFormView(SingleObjectMixin, FormView):

    template_name = 'articles/article_detail.html'
    form_class = UserFavoriteArticleForm
    model = Article

    def post(self, request, *args, **kwargs):
        if not request.user.is_authenticated:
            return redirect('accounts:login')
        self.object = self.get_object()
        form = self.get_form(self.form_class)
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)

    def form_valid(self, form):
        context = {
            'user': self.request.user,
            'article': self.get_object()
        }
        if UserFavoriteArticle.objects.filter(**context).exists():
            UserFavoriteArticle.objects.get(**context).delete()
        else:
            form.instance.user = context['user']
            form.instance.article = context['article']
            form.save()
        return super().form_valid(form)

    def get_success_url(self):
        return reverse(
            'articles:article_detail',
            kwargs={'pk': self.object.pk})


class ArticleView(View):

    def get(self, request, *args, **kwargs):
        view = ArticleDetailView.as_view()
        return view(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        view = UserFavoriteArticleFormView.as_view()
        return view(request, *args, **kwargs)


class ArticleCreateView(LoginRequiredMixin, CreateView):

    model = Article
    fields = ('title', 'synopsis', 'content')
    template_name_suffix = '_add_form'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        return reverse('articles:publications')


class PublicationListView(LoginRequiredMixin, ListView):

    model = Article
    context_object_name = 'articles'
    template_name = 'articles/publication_list.html'

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['headlines'] = ('Title', 'Synopsis', 'Created', '')
        return context


class UserFavoriteArticleListView(LoginRequiredMixin, ListView):

    model = UserFavoriteArticle
    context_object_name = 'favorites'
    template_name = 'articles/favorites.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['headlines'] = (
            'Title', 'Synopsis', 'Author', '')
        return context

    def get_queryset(self):
        return super().get_queryset().filter(user=self.request.user)

accounts/templates/accounts/login.html
{% extends "base_generic.html" %}

{% block title %}Login{% endblock %}

{% block style %}
    <style>
    .login-form {
    width: 360px;
    margin: 120px auto;
    }
    .login-form form {
        background: #FAFAFA;
        margin-bottom: 15px;
        padding: 30px;
    }
    .login-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    <div class="login-form">
        <form method="POST">
            <h2 class="text-center">Log in</h2>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-success btn-block" value="Log in">
        </form>
        <p class="text-center"><a href="{% url 'accounts:signup' %}">Create an Account</a></p>
    </div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends "base_generic.html" %}

{% block title %}Sign up{% endblock %}

{% block style %}
    <style>
    .signup-form {
    width: 480px;
    margin: 80px auto;
    }
    .signup-form form {
        background: #FAFAFA;
        margin-bottom: 15px;
        padding: 30px;
    }
    .signup-form h2 {
        margin: 0 0 15px;
    }
    .form-control, .btn {
        min-height: 38px;
        border-radius: 2px;
    }
    .btn {        
        font-size: 15px;
        font-weight: bold;
    }
</style>
{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    <div class="signup-form">
        <form method="POST">
            <h2 class="text-center">Sign up</h2>
            {% csrf_token %}
            {% bootstrap_form form %}
            <input type="submit" class="btn btn-success btn-block" value='Create account'>
        </form>
        <p class="text-center"><a href="{% url 'accounts:login' %}">Already have an account?</a></p>
    </div>
{% endblock %}

articles/templates/articles/article_add_form.html
{% extends "base_generic.html" %}

{% block title %}Create new article{% endblock %}

{% block content %}
    {% load bootstrap4 %}
    <div class="container">
        <h1 class="text-center">Your article</h1>
        <form method="POST">
            {% csrf_token %}
            {% bootstrap_form form %}
            <input class="btn btn-success" type="submit" value="Save">
        </form>
    </div>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends "base_generic.html" %}

{% block title %}Article detail{% endblock %}

{% block content %}
    <div class="container">
        <h1> {{ article.title }}</h1>
        <p> {{ article.content }}</p>
        <p> {{ article.author }}</p>
        <p> {{ article.created }}</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-success btn-sm" type="submit" value="To favorites">
        </form>
    </div>}
{% endblock %}

articles/templates/articles/article_list.html
{% extends "base_generic.html" %}

{% block title %} Articles {% endblock %}

{% block content %}
    <div class="container">
        {% if articles %}
            <h1 class="text-center pb-4">Articles</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        {% for headline in headlines %}
                            <th>{{ headline }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{ article.title }}</</td>
                            <td>{{ article.synopsis|truncatechars:20 }}</td>
                            <td>{{ article.author }}</td>
                            <td>{{ article.created }}</td>
                            <td>{{ article.created|timesince }}</td>
                            <td class="text-right"><a class="btn btn-info" href="{% url 'articles:article_detail' article.pk %}">Read</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No data available</p>
        {% endif %}
    </div>
{% endblock %}

articles/templates/articles/favorites.html
{% extends "base_generic.html" %}

{% block title %}Favorites{% endblock %}

{% block content %}
    <div class="container">
        {% if favorites %}
            <h1 class="text-center pb-4">My favorite articles</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        {% for headline in headlines %}
                            <th>{{ headline }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for favorite in favorites %}
                        <tr>
                            <td>{{ favorite.article.title }}</td>
                            <td>{{ favorite.article.synopsis }}</td>
                            <td>{{ favorite.article.author }}</td>
                            <td class="text-right"><a class="btn btn-info" href="{% url 'articles:article_detail' favorite.article.pk %}">Read</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No data available</p>
        {% endif %}
    </div>
{% endblock %}

articles/templates/articles/publication_list.html
{% extends "base_generic.html" %}

{% block title %}My publications{% endblock %}

{% block content %}
    <div class="container">
        {% if articles %}
            <h1 class="text-center pb-4">My publications</h1>
            <table class="table table-hover">
                <thead>
                    <tr>
                        {% for headline in headlines %}
                            <th>{{ headline }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                <tbody>
                    {% for article in articles %}
                        <tr>
                            <td>{{ article.title }}</td>
                            <td>{{ article.synopsis }}</td>
                            <td>{{ article.created }}</td>
                            <td class="text-right"><a class="btn btn-info" href="{% url 'articles:article_detail' article.pk %}">Read</a></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No data available</p>
        {% endif %}
        <p><a class="btn btn-success" href="{% url 'articles:article_add' %}">Create article</a></p>
    </div>
{% endblock %}

templates/base_generic.html
<!DOCTYPE html> 
<html lang="en">
<head>
    <title>
        {% block title %}{% endblock %}
    </title>
    {% block style %}
        <style>
            body { padding-top: 70px; }
        </style>
    {% endblock %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {% bootstrap_messages %}
</head>
    <body>
        {% include "navigation.html" %}

        {% block content %}{% endblock %}
    </body>
</html>

templates/navigation.html
<nav class="navbar fixed-top navbar-expand-lg navbar-dark" style="background-color: #505050">
    <a class="navbar-brand" href="#">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-book" viewBox="0 0 16 16">
              <path d="M1 2.828c.885-.37 2.154-.769 3.388-.893 1.33-.134 2.458.063 3.112.752v9.746c-.935-.53-2.12-.603-3.213-.493-1.18.12-2.37.461-3.287.811V2.828zm7.5-.141c.654-.689 1.782-.886 3.112-.752 1.234.124 2.503.523 3.388.893v9.923c-.918-.35-2.107-.692-3.287-.81-1.094-.111-2.278-.039-3.213.492V2.687zM8 1.783C7.015.936 5.587.81 4.287.94c-1.514.153-3.042.672-3.994 1.105A.5.5 0 0 0 0 2.5v11a.5.5 0 0 0 .707.455c.882-.4 2.303-.881 3.68-1.02 1.409-.142 2.59.087 3.223.877a.5.5 0 0 0 .78 0c.633-.79 1.814-1.019 3.222-.877 1.378.139 2.8.62 3.681 1.02A.5.5 0 0 0 16 13.5v-11a.5.5 0 0 0-.293-.455c-.952-.433-2.48-.952-3.994-1.105C10.413.809 8.985.936 8 1.783z"/>
        </svg>
    </a>
     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mr-auto">

            <li class="nav-item">
                <a class="nav-link" href="{% url 'articles:articles' %}">Articles</a>
            </li>
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'articles:publications' %}">Publications</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'articles:favorites' %}">Favorites</a>
                </li>
            {% endif %}
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                   <a class="nav-link" href="#">Loged as {{ user }}</a>
                </li>
                <li class="nav-item ml-auto">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log out</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign up</a>
                </li>
            {% endif %}
        </ul>
</nav>